"""add campus_code in request model

Revision ID: 371cd73c3bae
Revises: 888416120601
Create Date: 2025-05-25 20:26:31.828854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371cd73c3bae'
down_revision: Union[str, None] = '888416120601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('campus_code', sa.String(), nullable=False))
    op.create_foreign_key(None, 'requests', 'campus', ['campus_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'campus_code')
    # ### end Alembic commands ###
