"""Update request table with user attribute to be updated in team

Revision ID: ac9f06ae07e1
Revises: abefa3f7285b
Create Date: 2025-05-25 15:29:04.956829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9f06ae07e1'
down_revision: Union[str, None] = 'abefa3f7285b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('user_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'user_id')
    # ### end Alembic commands ###
