"""Create requests table

Revision ID: c3d2768c17bc
Create Date: 2025-07-18 17:36:30.954779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d2768c17bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

request_type_enum = sa.Enum(
    'approve_team',
    'delete_team',
    'remove_team_member',
    'add_team_member',
    name='requesttypeenum'
)
request_status_enum = sa.Enum(
    'pendent',
    'approved',
    'rejected',
    name='requeststatusenum'
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('requests',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('request_type', request_type_enum, nullable=False),
        sa.Column('team_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('competition_id', sa.UUID(as_uuid=True), nullable=True),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('campus_code', sa.String(), nullable=False),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('reason_rejected', sa.String(), nullable=True),
        sa.Column('status', request_status_enum, server_default='pendent', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')

    # ### end Alembic commands ###

